// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2kDtZ9OwNiSTYT7LZMdC03pd8kh1j4Nc',
    appId: '1:805775935922:web:3d1247b2eea6a5591e7cab',
    messagingSenderId: '805775935922',
    projectId: 'ugandaschoolsystem-d1ca3',
    authDomain: 'ugandaschoolsystem-d1ca3.firebaseapp.com',
    storageBucket: 'ugandaschoolsystem-d1ca3.firebasestorage.app',
    measurementId: 'G-JQ6JRLBGMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbXyp_Ei-qbTESrtpbpnnWV7qHwcw5XBg',
    appId: '1:805775935922:android:c3e545390623d4d71e7cab',
    messagingSenderId: '805775935922',
    projectId: 'ugandaschoolsystem-d1ca3',
    storageBucket: 'ugandaschoolsystem-d1ca3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm967DYwzUH1J3scyRNm3m6TRJ87k8qNs',
    appId: '1:805775935922:ios:9674e71247c28d341e7cab',
    messagingSenderId: '805775935922',
    projectId: 'ugandaschoolsystem-d1ca3',
    storageBucket: 'ugandaschoolsystem-d1ca3.firebasestorage.app',
    iosBundleId: 'com.example.schoolSystemApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2kDtZ9OwNiSTYT7LZMdC03pd8kh1j4Nc',
    appId: '1:805775935922:web:675e8fc2c4478abd1e7cab',
    messagingSenderId: '805775935922',
    projectId: 'ugandaschoolsystem-d1ca3',
    authDomain: 'ugandaschoolsystem-d1ca3.firebaseapp.com',
    storageBucket: 'ugandaschoolsystem-d1ca3.firebasestorage.app',
    measurementId: 'G-NN6WZ46QY6',
  );
}
